name: Test

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Test
              run: |
                  import-module appx -usewindowspowershell
                  (get-appxpackage micro*win*appruntime*).packagefullname
